import { Component, OnInit } from '@angular/core';

@Component({
	selector: 'app-metric',
	templateUrl: './metric.component.html'
})
export class MetricComponent implements OnInit {

	data: any; header: any;

	constructor() {
		this.data = [];
		this.header = [
			{ id: 'name', name: 'Game Report', is_search: 1, st_col: 'name', st_type: 1 },
			{ id: 'desc', name: 'Overview game data (Install, DAU, Rev, PU)', is_search: 1, st_col: 'desc', st_type: 1 }
		]
	}

	ngOnInit() {
		this.helpFetchData();
	}

	helpFetchData() {
		this.data = [
			{ 'name': 'NRU0', 'desc': 'Number of accounts that log­in to the game for the first time from install acquired in day' },
			{ 'name': 'NRU', 'desc': 'Number of accounts that log­in to the game for the first time in day' },
			{ 'name': 'A1 (DAU)', 'desc': 'Daily Active Users' },
			{ 'name': 'A7', 'desc': 'Weekly Active Users (unique)' },
			{ 'name': 'A30 (MAU)', 'desc': 'Monthly Active Users (unique)' },
			{ 'name': 'A1 (DAU)', 'desc': 'Daily Active Users' },
			{ 'name': 'PU in day', 'desc': '' },
			{ 'name': 'PU in 7 days', 'desc': 'Unique PU in 7 days' },
			{ 'name': 'PU in 30 days', 'desc': 'Unique PU in 30 days' },
			{ 'name': 'CR', 'desc': 'Conversion rate from DAU to PU' },
			{ 'name': 'Rev in day', 'desc': 'Conversion rate from DAU to PU' },
			{ 'name': 'Rev in 7 day', 'desc': 'Accumulated rev in 7 days' },
			{ 'name': 'Rev in 30 day', 'desc': 'Accumulated rev in 30 days' },
			{ 'name': 'ARPPU', 'desc': 'Average revenue per paying user' },
			{ 'name': 'Organic', 'desc': 'Number of accounts that generated by organic installations (track by tracking tool such as Appsflyer)' },
			{ 'name': 'Paid Media', 'desc': 'Number of accounts that generated by non­organic installations (track by tracking tools such as Appsflyer' }
		];
	}
}
